// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: create_svc.proto

package create_svc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CreateClientService_CreateNewClient_FullMethodName = "/create_svc.CreateClientService/CreateNewClient"
)

// CreateClientServiceClient is the client API for CreateClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateClientServiceClient interface {
	CreateNewClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
}

type createClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateClientServiceClient(cc grpc.ClientConnInterface) CreateClientServiceClient {
	return &createClientServiceClient{cc}
}

func (c *createClientServiceClient) CreateNewClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, CreateClientService_CreateNewClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateClientServiceServer is the server API for CreateClientService service.
// All implementations must embed UnimplementedCreateClientServiceServer
// for forward compatibility
type CreateClientServiceServer interface {
	CreateNewClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	mustEmbedUnimplementedCreateClientServiceServer()
}

// UnimplementedCreateClientServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCreateClientServiceServer struct {
}

func (UnimplementedCreateClientServiceServer) CreateNewClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewClient not implemented")
}
func (UnimplementedCreateClientServiceServer) mustEmbedUnimplementedCreateClientServiceServer() {}

// UnsafeCreateClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateClientServiceServer will
// result in compilation errors.
type UnsafeCreateClientServiceServer interface {
	mustEmbedUnimplementedCreateClientServiceServer()
}

func RegisterCreateClientServiceServer(s grpc.ServiceRegistrar, srv CreateClientServiceServer) {
	s.RegisterService(&CreateClientService_ServiceDesc, srv)
}

func _CreateClientService_CreateNewClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateClientServiceServer).CreateNewClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreateClientService_CreateNewClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateClientServiceServer).CreateNewClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateClientService_ServiceDesc is the grpc.ServiceDesc for CreateClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "create_svc.CreateClientService",
	HandlerType: (*CreateClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewClient",
			Handler:    _CreateClientService_CreateNewClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "create_svc.proto",
}
